### ISSUE TITLE
Check the waveform when / after the XSI test is executed

### ISSUE THREAD

**Issue by ziyue-pan** [gsmecher/pyxsi#2]
Thanks for the decent code and documents. I have a further question:

Is it able to check the waveform in vivado when / after the XSI test is executed?

**Comment by gsmecher** [comment]
Yes - if you use the "trace_all" call and set the "tracefile" argument (xsim.wdb by default), a waveform database will be produced during cosimulation. I use something like the following shell script to open these waveform files from a bash prompt:

```
#!/bin/sh

. /opt/xilinx/Vivado/2021.1/settings64.sh

echo vivado -mode tcl -source /dev/null -tclargs "$1"

vivado -mode tcl -tclargs "$1" <<EOF
        start_gui
        open_wave_database [lindex \$argv 0]
        add_wave *

        proc re {} {
                upvar argv fn
                close_sim -force
                open_wave_database [lindex \$fn 0]
                add_wave *
        }
EOF
```

Note that the xsim kernel is not always diligent about flushing the .wdb - if a cosimulation crashes or otherwise terminates early, an incomplete .wdb file is sometimes left behind. These waveforms open in Vivado but do not contain complete waveform data.
